### ISSUE TITLE
dev 出错

### ISSUE THREAD

**Issue by moxun33** [lanten/electron-antd#1]
Hi, 我npm i 之后 npm start 出错了。该如何解决？谢谢！

```
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at BrowserSync.cb (/Users/mo/Desktop/electron-antd-master/scripts/serve.js:34:16)
    at /Users/mo/Desktop/electron-antd-master/node_modules/browser-sync/lib/browser-sync.js:278:12
    at /Users/mo/Desktop/electron-antd-master/node_modules/browser-sync/lib/utils.js:283:25
    at executeTask (/Users/mo/Desktop/electron-antd-master/node_modules/browser-sync/lib/browser-sync.js:170:13)
    at Object.initUserPlugins [as fn] (/Users/moxingxum/Desktop/electron-antd-master/node_modules/browser-sync/lib/async.js:317:9)
    at /Users/mo/Desktop/electron-antd-master/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/Users/mo/Desktop/electron-antd-master/node_modules/browser-sync/lib/utils.js:276:13)

```

**Comment by lanten** [comment]
我在[scripts/serve.js中移除了一行错误代码](https://github.com/lanten/electron-antd/commit/36b0cacd86676103bca0fda2fe64e2f3c2ff2aac)
现在 `npm start` 应该可以正常运行
